# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Finish/MonkeyFinder.sln'
    arguments: '-c Release -f net6.0-android'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*-Signed.aab'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
